name: Vultr Continuous Deployment

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Install vultr-cli
        uses: techknowlogick/action-vultr@v2
        with:
          token: ${{ secrets.VULTR_API_KEY }}
      - run: vultr-cli account  

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     - uses: actions/checkout@master
#     - uses: actions/setup-node@master
#       width:
#       node-version: 12
#     - run: npm ci
#     - run: npm run build
#     - uses: 


#     ${{secrets.VULTR_API_KEY}}